eureka:
  image: "lreimer/cloud-native-eureka"
  hostname: eureka
  ports:
    - "8761:8761"

config:
  image: "lreimer/cloud-native-config"
  hostname: config
  links:
    - eureka
  environment:
    EUREKA_HOST: eureka
    EUREKA_PORT: 8761
  ports:
    - "8888:8888"

dotnet:
  image: "lreimer/cloud-native-dotnet"
  hostname: dotnet
  links:
    - eureka
    - config
  environment:
    EUREKA_HOST: eureka
    EUREKA_PORT: 8761
  ports:
    - "8080:8080"
    - "5000:5000"
