apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  # use NodePort here to be able to access the port on each node
  type: NodePort
  ports:
  - port: 8761
  selector:
    app: eureka
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka
spec:
  replicas: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: "lreimer/cloud-native-eureka"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 8761
        livenessProbe:
          httpGet:
            path: /admin/health
            port: 8761
          initialDelaySeconds: 60
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /admin/info
            port: 8761
          timeoutSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: config
  labels:
    app: config
spec:
  # use NodePort here to be able to access the port on each node
  type: NodePort
  ports:
  - port: 8888
  selector:
    app: config
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: config
spec:
  replicas: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
      - name: config
        image: "lreimer/cloud-native-config"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 8888
        livenessProbe:
          httpGet:
            path: /admin/health
            port: 8888
          initialDelaySeconds: 90
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /admin/info
            port: 8888
          timeoutSeconds: 30
        env:
        - name: EUREKA_HOST
          value: eureka
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet
  labels:
    app: dotnet
spec:
  # use NodePort here to be able to access the port on each node
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: dotnet
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dotnet
spec:
  replicas: 2
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      containers:
      - name: dotnet
        image: "lreimer/cloud-native-dotnet"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /admin/info
            port: 8080
          initialDelaySeconds: 90
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /admin/info
            port: 8080
          timeoutSeconds: 30
        env:
        - name: EUREKA_HOST
          value: eureka